version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3

commands:
  create_ec2:
    description: Creates an EC2 instance on aws
    steps:
      - run:
          name: Create Cloudformation Stack for EC2
          command: |
            aws cloudformation deploy \
              --template-file create_ec2.yml \
              --stack-name circleci-infra-create-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
      - run:
          name: install_failed
          command: echo "[X] Error!! Could not install dependencies"
          when: on_fail
      - run:
          name: check stack events
          command: | 
            aws cloudformation describe-stack-events \
              --stack-name circleci-infra-create-${CIRCLE_WORKFLOW_ID:0:5}
          when: on_fail

# Define the jobs we want to run for this project
jobs:
  print_hello_world:  # Choose any name, such as `build`
      docker:
        - image: circleci/node:10.16.3
      steps:
        - checkout
        - run: echo "hello world"

  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - create_ec2

# Sequential workflow
workflows:
  create_ec2_stack:
    jobs:
      - print_hello_world
      - create_infrastructure